Repository GlueOps/platform-helm-chart-platform, pull requests merged in 2024-06, with the labels that each got.

#305 major: bump version for next release that disables WAF deletions
  Chart.yaml
  README.md
Labels: include-in-release-notes, patch, major

#274 feat: add remoteWrite to cortex in prometheus
  templates/application-kube-prometheus-stack.yaml
Labels: enhancement, include-in-release-notes, patch, minor

#330 major: delete strimzi
  templates/application-strimzi.yaml
Labels: Review effort [1-5]: 1, include-in-release-notes, major

#340 feat: bump for next rc
  Chart.yaml
  README.md
Labels: enhancement, Review effort [1-5]: 1, include-in-release-notes, patch, minor

#343 fix: revert external dns back to v6
  Chart.yaml
  README.md
  templates/application-external-dns.yaml
Labels: Review effort [1-5]: 1, include-in-release-notes, patch, bug fix

#344 feat: update cert-manager CRDs
  templates/application-cert-manager-crd.yaml
Labels: enhancement, include-in-release-notes, minor

#350 fix: remove prometheus remote write
  Chart.yaml
  README.md
  templates/application-kube-prometheus-stack.yaml
Labels: include-in-release-notes, patch

#351 chore: bump chart.yaml for release v0.45.0
  Chart.yaml
  README.md
Labels: include-in-release-notes, patch
