Repository GlueOps/platform-helm-chart-platform, pull requests merged in 2024-10, with the labels that each got.

#459 Major removing loki exporter and waf/webacl keys
  Chart.yaml
  README.md
  main.tf
Labels: documentation, Review effort [1-5]: 2, include-in-release-notes, patch, major

#461 fix: replaces
  Chart.yaml
  README.md
  main.tf
Labels: Review effort [1-5]: 2, include-in-release-notes, patch

#462 [skip actions] synced file(s) with internal-GlueOps/github-shared-files-sync
  .github/release.yml
Labels: Review effort [1-5]: 1, Configuration changes, sync

#466 fix: remove hardcoded captain domain for new otel stack
  README.md
  values.yaml
Labels: documentation, enhancement, Review effort [1-5]: 2, include-in-release-notes

#464 [skip actions] synced file(s) with internal-GlueOps/github-shared-files-sync
  .github/release.yml
Labels: Review effort [1-5]: 1, sync

#526 feat: update chart.yaml to version: 0.52.0
  Chart.yaml
  README.md
Labels: enhancement, Review effort [1-5]: 1, include-in-release-notes, patch, minor

#528 Fix bump nginx version to v1.11.3
  Chart.yaml
  README.md
  templates/application-nginx-public.yaml
Labels: documentation, Review effort [1-5]: 1, include-in-release-notes, patch
