Repository GlueOps/platform-helm-chart-platform, pull requests merged in 2025-08, with the labels that each got.

#770 fix: loki canary is using docker.io and not one of our mirrors
  templates/application-loki.yaml
Labels: include-in-release-notes, patch

#769 feat: migrate external-dns from bitnami to github
  README.md
  templates/application-external-dns.yaml
  values.yaml
Labels: enhancement, Possible security concern, include-in-release-notes, patch, minor, Review effort 2/5

#780 chore: bump chart
  Chart.yaml
  README.md
Labels: include-in-release-notes, patch, Review effort 1/5
