Repository GlueOps/platform-helm-chart-platform, pull requests merged in 2025-04, with the labels that each got.

#630 Change registry
  README.md
  templates/application-backups-and-exports.yaml
  templates/application-cert-manager.yaml
  templates/application-cluster-info-page.yaml
  templates/application-dex.yaml
  templates/application-external-dns.yaml
  templates/application-external-secrets.yaml
  templates/application-fluent-operator.yaml
  templates/application-glueops-alerts.yaml
  templates/application-keda.yaml
  templates/application-kube-prometheus-stack.yaml
  templates/application-loki-alert-group-controller.yaml
  templates/application-loki.yaml
  templates/application-metacontroller.yaml
  templates/application-network-exporter.yaml
  templates/application-nginx-public.yaml
  templates/application-promtail.yaml
  templates/application-pull-request-bot.yaml
  templates/application-qr-code-generator.yaml
  templates/application-vault-init-controller.yaml
  templates/application-vault.yaml
  values.yaml
Labels: Review effort 2/5

#670 Update Chart.yaml
  Chart.yaml
  README.md
Labels: Review effort 1/5

#671 Update Chart.yaml
  Chart.yaml
  README.md
Labels: Review effort 1/5

#673 Update Chart.yaml
  Chart.yaml
  README.md
Labels: Review effort 1/5

#675 Update Chart.yaml
  Chart.yaml
  README.md
Labels: Review effort 1/5

#682 fix: downgrading vault back to old version
  Chart.yaml
  README.md
Labels: include-in-release-notes, patch, Review effort 1/5

#685 hotfix: rolling back vault
  Chart.yaml
  README.md
Labels: Review effort 1/5

#690 major: migrating from pomerium to oauth2proxy
  README.md
  TERRAFORM.md
  main.tf
  templates/application-cluster-info-page.yaml
  templates/application-dex.yaml
  templates/application-glueops-alerts.yaml
  templates/application-kube-prometheus-stack.yaml
  templates/application-nginx-glueops-platform-oauth2.yaml
  templates/application-oauth2.yaml
  templates/application-pomerium-post-deploy.yaml
  templates/application-pomerium.yaml
  templates/application-vault.yaml
  values.yaml
Labels: Possible security concern, Review effort 2/5

#694 feat: adding csrf per request and requiring prompt if there are multi…
  templates/application-oauth2.yaml
Labels: enhancement, include-in-release-notes, minor, Review effort 1/5

#693 fixing redirect
  main.tf
  templates/application-cluster-info-page.yaml
  templates/application-kube-prometheus-stack.yaml
  templates/application-oauth2.yaml
  templates/application-vault.yaml
Labels: Review effort 1/5

#692 Update Chart.yaml
  Chart.yaml
  README.md
Labels: Review effort 1/5

#701 adding node toleration/selector for nginx-glueops/oauth2
  Chart.yaml
  README.md
  templates/application-nginx-glueops-platform-oauth2.yaml
  templates/application-oauth2.yaml
Labels: Review effort 1/5
