Repository GlueOps/platform-helm-chart-platform, pull requests merged in 2025-03, with the labels that each got.

#616 fix: otel-operator.yml argocd reconciling issue
  otel/otel-operator.yaml
Labels: include-in-release-notes, patch, Review effort 1/5

#621 Update values.yaml
  README.md
  templates/application-fluent-operator.yaml
  values.yaml
Labels: Review effort 1/5

#636 Feat/update cert manager
  README.md
  templates/application-cert-manager.yaml
  values.yaml
Labels: enhancement, include-in-release-notes, patch, minor, Review effort 2/5
