Repository GlueOps/platform-helm-chart-platform, pull requests merged in 2025-05, with the labels that each got.

#702 chore: move ingress nginx for glueops-platform and the oauth2 proxy setup into it's own subdirectory
  templates/glueops-platform-ingress/application-nginx-glueops-platform-oauth2.yaml
  templates/glueops-platform-ingress/application-oauth2.yaml
Labels: Possible security concern, include-in-release-notes, patch, Review effort 2/5

#674 parameterize enabling chisel-proxy
  README.md
  templates/application-nginx-public.yaml
  templates/glueops-platform-ingress/application-nginx-glueops-platform-oauth2.yaml
  values.yaml
Labels: Review effort 2/5

#708 Feat/update naming conventions in aws
  Chart.yaml
  README.md
  main.tf
  values.yaml
Labels: Review effort 2/5

#711 Add backup prefix
  Chart.yaml
  README.md
  main.tf
  templates/application-backups-and-exports.yaml
  templates/application-cert-manager.yaml
  templates/application-vault-init-controller.yaml
  templates/glueops-platform-ingress/application-oauth2.yaml
  values.yaml
Labels: Review effort 2/5

#718 Feat/update image tags
  Chart.yaml
  README.md
  templates/glueops-platform-ingress/application-oauth2.yaml
  values.yaml
Labels: Review effort 1/5

#719 Fix missing prefix
  Chart.yaml
  README.md
  templates/application-vault-init-controller.yaml
Labels: Review effort 1/5

#720 feat: Add PRCHECKLIST using Pull Request Checklist Buddy
  PRCHECKLIST
Labels: enhancement, include-in-release-notes, minor

#725 fix: monitoring_upgrade branch
  templates/application-kube-thanos-stack.yaml
Labels: include-in-release-notes, patch, Review effort 1/5

#730 fix otel-operator.yaml to avoid argocd reconcile issues
  otel/otel-operator.yaml
Labels: Review effort 2/5
